name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: x64

      - run: pip install nox
      - run: pip install nox_poetry
      - run: pip install poetry
      - run: pip install poetry-dynamic-versioning

      - name: Run nox on Linux
        run: nox

      - run: poetry build
      - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
